baseURL = "http://example.com/"
languageCode = "en-us"
title = "ADAMZVX"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "tentang dan opini"
    githubUsername = "#"
    accent = "whitesmoke"
    showBorder = false
    backgroundColor = "DarkSlateGray"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "php", "python" ]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:adammmfs@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/adamzvx/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/adam.zvx/"
    name = "instagram"
    weight = 3

[[menu.icon]]
    url = "https://t.me/adamzvx/"
    name = "telegram"
    weight = 4

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5	